### ISSUE TITLE
The Logitech / Saitek X-56 settings don't work

### ISSUE THREAD

**Issue by cgoodric** [edemirkan/tftc-joystick-resources#3]
The Logitech HOTAS software won't load the pr0 file.

Only the throttle axis works and is inverted for some reason.

The buttons are reversed from stick to throttle.

The ship just yaws constantly even with rudder disabled. No joystick inputs work.

**Comment by edemirkan** [comment]
Hi @cgoodric 
Community support is provided at our [Discord Server]( https://discord.gg/GFVjySqEfm ). You can post in the `#joysticks-and-controllers` channel and ask for help from the community
